### ISSUE TITLE
Fix incompatibility with the built-in "hl-line-mode"

### ISSUE THREAD

**Issue by salutis** [wyuenho/all-the-icons-dired#13]
The icons break the highlight provided by the built-in `hl-line-mode`:

<img width="362" alt="Screen Shot 2021-12-23 at 12 43 05" src="https://user-images.githubusercontent.com/1158274/147235998-7a48dafb-f007-48ad-97aa-418f21663891.png">

(Tested with the built-in Modus Operandi theme.)

**Comment by protesilaos** [comment]
I can reproduce this.  Though it is not related to the active theme.

**Comment by wyuenho** [comment]
This isn't a bug in all-the-icons-dired but rather a bug in hl-line-mode and emacs in general. It's not possible to set the background alpha transparency of a face in emacs, and the hl-line-mode overlay is interfering with all-the-icons-dired's. Your best bet is to advice `hl-line-move`, which is called by both `global-hl-line-highlight` and `hl-line-highlight`. In the advice you can find the icon overlay and set the background of `font-lock-face`.

**Comment by seagle0128** [comment]
@wyuenho I am experiencing the same issue. I went through the codes quickly, and think it's caused by overlay. It was introduced by https://github.com/jtbm37/all-the-icons-dired/pull/24.

https://github.com/wyuenho/all-the-icons-dired/blob/147ed0dfd1034a686795a08dc63e2c293128597e/all-the-icons-dired.el#L103-L104

**Comment by wyuenho** [comment]
There's no good fix for this short of emacs start supporting alpha transparency of a face.
